---
openapi: 3.0.3
info:
  title: Library
  version: 1.0.0
paths:
  /publishers/{publisherId}/books/{bookId}:
    parameters:
    - $ref: "#/components/parameters/PublisherId"
    - $ref: "#/components/parameters/BookId"
    delete:
      operationId: deleteBook
      description: Delete a single book.
      parameters:
        - in: header
          name: If-Match
          schema:
            type: string
          description: |
            The etag of the book.
            If this is provided, it must match the server's etag.
      responses:
        '204':
          description: Book was deleted
components:
  parameters:
    PublisherId:
      name: publisherId
      in: path
      description: The id of the book publisher.
      required: true
      schema:
        type: string
    BookId:
      name: bookId
      in: path
      description: The id of the book.
      required: true
      schema:
        type: string
  schemas:
    Book:
      description: A representation of a single book.
      properties:
        name:
          type: string
          description: |
            The name of the book.
            Format: publishers/{publisher}/books/{book}
        isbn:
          type: string
          description: |
            The ISBN (International Standard Book Number) for this book.
        title:
          type: string
          description: The title of the book.
        authors:
          type: array
          items:
            type: string
          description: The author or authors of the book.
        rating:
          type: number
          format: float32
          description: The rating assigned to the book.
