---
openapi: 3.0.3
info:
  title: Library
  version: 1.0.0
components:
  schema:
    Book:
      description: A representation of a single book.
      properties:
        path:
          type: string
          description: |
            The path of the book.
            Format: publishers/{publisher}/books/{book}
        author:
          $ref: '#/components/schemas/Author'
          description: |
            The author or authors of the book.

            By default, only the `path` field of the author is populated.
            However, the full author can be retrieved by specifying the
            FULL_WITH_AUTHOR view. This **will not** dereference resource
            references within the author, such as `Author.pen_names`; only
            the `path` subfield of these fields will be populated.
