---
openapi: 3.0.3
info:
  title: Library
  version: 1.0.0
paths: {}
components:
  schemas:
    Book:
      description: This book will self-destruct.
      type: object
      properties:
        name:
          type: string
          description: |
            The name of the book.
            Format: publishers/{publisher}/books/{book}
      oneOf:
      - type: object
        properties:
          expireTime:
            type: string
            format: date-time
            description: |
              Timestamp in UTC of when this resource is considered expired.
      - type: object
        properties:
          ttlSeconds:
            type: integer
            description: |
              The TTL for this resource in seconds.
              When this value is passed as input it is returned as the equivalent
              expireTime on output.
            writeOnly: true
