---
buttons:
  - text: Explore the AEPs
    href: /general
  - text: Learn how it works
    href: /1
shortcuts:
  - title: Curious about the basics?
    description: |
      AEPs are a combination of design guidance and a system to manage
      and track that guidance. Learn more about how the AEP program works in
      the first AEP!
    button:
      href: /1
      text: Read AEP-1
  - title: Want to help?
    description: |
      Interested in helping with AEPs? Contribute by proposing new guidance,
      commenting on existing AEPs, or fixing typos. All contributions are
      welcome!
    button:
      href: /contributing
      text: Contribute to the project
  - title: Want to use AEPs in your organization?
    description: |
      AEPs were adapted from [Google's AIP project](https://google.aip.dev/), 
      and offer benefits and tooling that result in better designed APIs.
    button:
      href: /adopting
      text: Learn more
  - title: Still have questions?
    description: |
      Free free to take a look at the <a href="/faq">frequently asked
      questions</a>. If you don't find an answer there, file an issue on our
      GitHub repository.
    button:
      href: https://github.com/aep-dev/aep.dev/issues
      text: Ask us on GitHub
