---
openapi: 3.0.3
info:
  title: Library
  version: 1.0.0
paths:
  /publishers/{publisherId}/books:
    parameters:
      - name: publisherId
        in: path
        description: The publisher to list books for.
        required: true
        schema:
          type: string
    get:
      operationId: listBooks
      description: Get a collection of books.
      parameters:
        - name: pageToken
          in: query
          description: |
            The page token.
            If a `next_page_token` value was received on a previous
            ListBooks call, providing it here will return the next page.
          schema:
            type: string
        - name: maxPageSize
          in: query
          description: |
            The maximum number of books to return.
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListBooksResponse'
components:
  schemas:
    ListBooksResponse:
      type: object
      description: A representation of a collection of books.
      properties:
        results:
          type: array
          items:
            '$ref': '#/components/schemas/Book'
        nextPageToken:
          type: string
          description: |
            The token to retrieve the next page. This is populated if and only
            if there are more pages.
    Book:
      description: A representation of a single book.
      type: object
      properties:
        name:
          type: string
          description: |
            The name of the book.
            Format: publishers/{publisher}/books/{book}
        isbn:
          type: string
          description: |
            The ISBN (International Standard Book Number) for this book.
        title:
          type: string
          description: The title of the book.
        authors:
          type: array
          items:
            type: string
          description: The author or authors of the book.
        rating:
          type: number
          description: The rating assigned to the book.
