openapi: 3.0.3
info:
  title: Library
  version: 1.0.0
paths:
  /publishers/{publisherId}/books:BatchGet:
    parameters:
      - name: publisherId
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: BatchGetBooks
      description: Get multiple books in a batch.
      parameters:
        - name: names
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
components:
  schemas:
    Book:
      description: A representation of a single book.
      properties:
        name:
          type: string
          description: |
            The name of the book.
            Format: publishers/{publisher}/books/{book}
        isbn:
          type: string
          description: |
            The ISBN (International Standard Book Number) for this book.
        title:
          type: string
          description: The title of the book.
        authors:
          type: array
          items:
            type: string
          description: The author or authors of the book.
        rating:
          type: number
          format: float
          description: The rating assigned to the book.
