---
openapi: 3.0.3
info:
  title: Library
  version: 1.0.0
components:
  schema:
    Book:
      description: A representation of a single book.
      x-declarative-friendly: true
      properties:
        name:
          type: string
          description: |
            The name of the book.
            Format: publishers/{publisher}/books/{book}
        # Additional fields...
