---
name: test
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v3
      - name: Generate all static pages, and build site.
        run: ./scripts/build.sh
