---
name: test
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - uses: actions/checkout@v3
      - name: Install the site-generator
        run: pip install -r requirements.txt
      - name: Build the site.
        run: aip-site-gen . /out
